Fix default hostname setup
bitnami/bitnami-docker-opencart pull request #89
Opened 2020-10-27 08:47 UTC by juan131

**Description of the change**

This PR ensure the "update hostname" function is called during the initialisation to avoid a wrong configuration in the `HTTPS_SERVER` and `HTTPS_CATALOG` settings.

**Benefits**

Valid default configuration.

**Possible drawbacks**

None

**Applicable issues**

- fixes https://github.com/bitnami/bitnami-docker-opencart/issues/55

2020-10-28 10:54 UTC, dani8art requested changes

2020-10-28 10:54 UTC, dani8art commented on 3/debian-10/rootfs/opt/bitnami/scripts/libopencart.sh
> +#   $1 - PHP constant name
```suggestion
#   $1 - hostname in the form <host>[:<port>]
```

2020-10-28 10:54 UTC, dani8art commented on 3/debian-10/rootfs/opt/bitnami/scripts/libopencart.sh
> +    opencart_conf_set HTTP_SERVER "http://${hostname}/"
I don't know if the `<port>` would be needed. I mean, by default this image will use `8080` and `8443` and I guess opencart will use this HTTP_SERVER to redirect and build URL internally then there could be some URL pointing to `http://${hostname}/my-path` when the actually should be pointed to `http://${hostname}:8080/my-path`

2020-10-29 08:05 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libopencart.sh
> +    opencart_conf_set HTTP_SERVER "http://${hostname}/"
You're right.. The "external port" is needed

2020-10-29 09:06 UTC, dani8art approved these changes

2020-10-29 10:38 UTC, merged